### ISSUE TITLE
Base64 is wrongly defined as encryption scheme

### ISSUE THREAD

**Issue by Hetti** [srdnlen/srdnlenctf-2023_public#1]
~~At least~~ In the Writeup for [Urban Odissey](https://github.com/srdnlen/srdnlenctf-2023_public/blob/main/foren_Urban%20Odyssey/writeup.md#urban-odissey) Base64 is wrongly defined as encryption scheme.

Base64 is an encoding scheme as defined in [RFC 4648](https://www.rfc-editor.org/rfc/rfc4648).

**Comment by davidemaiorca** [comment]
We fixed the WU. Thank you!
